#
# Circle CI 2.0 Docs
# 
# For info, see: https://circleci.com/docs/2.0/
#

version: 2
jobs:
  build:
    docker:
      - image: docker:1.13.1-git
        environment:
          DOCKER_PROJECT_NAME: docker-nginx-reverse-proxy
    working_directory: ~/docker-nginx-reverse-proxy
    steps:
      - checkout
      - setup_remote_docker

      # Build and Push to Docker Hub (branch and latest (sync'd to master)) 
      - run: |
          docker build -t newtonsystems/$DOCKER_PROJECT_NAME:$CIRCLE_BRANCH ./tools/docker-grpc-tools
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push newtonsystems/$DOCKER_PROJECT_NAME:$CIRCLE_BRANCH
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag newtonsystems/$DOCKER_PROJECT_NAME:$CIRCLE_BRANCH newtonsystems/$DOCKER_PROJECT_NAME:latest
              docker push newtonsystems/$DOCKER_PROJECT_NAME:latest
          fi
